config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :parkings do
    resources :bookings, only: [:create, :index]
  end
  resources :bookings, only: :destroy do
    member do
      patch :validate
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :parking
  validates :booking_start, :booking_end, presence: true
end

app/models/parking.rb
class Parking < ApplicationRecord
  has_many :bookings
  belongs_to :user
  has_many_attached :photos

  validates :address, :height, :width, :length, :description, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :parkings
  has_one_attached :photo

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_parking, only: %i[create]
  before_action :authenticate_user!


  def index
  end

  def validate
    @booking = Booking.find(params[:id])
    @booking.confirmation = true
    @booking.save!
    redirect_to profile_path()
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.parking = @parking
    @booking.save!
    redirect_to profile_path(@booking.user)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to profile_path, status: :see_other
  end


  private

  def set_parking
    @parking = Parking.find(params[:parking_id])
  end

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def booking_params
    params.require(:booking).permit(:booking_start, :booking_end)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def profile
    @parkings = Parking.where(user: current_user)
    @bookings = Booking.where(user: current_user)
    @parkings.each do |parking|
      @bookings_parking = parking.bookings
    end
  end

  private

  def set_parking
    @parking = Parking.find(params[:parking_id])
  end

  def booking_params
    params.require(:booking).permit(:arrival, :depart)
  end

  def parking_params
    params.require(:parking).permit(:address, photos: [])
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController

  before_action :set_parking, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index, :show, :create]

  def index
    if params[:query].present?
      @parkings = Parking.where("address ILIKE ?", "%#{params[:query]}%")
    else
      @parkings = Parking.all
    end
    @markers = @parkings.geocoded.map do |parking|
      {
        lat: parking.latitude,
        lng: parking.longitude,
        info_window: render_to_string(partial: "info_window", locals: {parking: parking})
      }
    end
  end

  def show
    @booking = Booking.new
    # The `geocoded` scope filters only flats with coordinates
    @parking_map = Parking.where(id: params[:id])
    @markers = @parking_map.geocoded.map do |park|
      {
        lat: park.latitude,
        lng: park.longitude
      }
    end
  end

  def new
    @parking = Parking.new
  end

  def create
    @parking = Parking.new(parking_params)
    @parking.user = current_user
    if @parking.save!
      redirect_to parking_path(@parking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @parking = Parking.find(params[:id])
  end

  def update
    @parking = Parking.find(params[:id])
    @parking.update(parking_params)
    # No need for app/views/restaurants/update.html.erb
    redirect_to parking_path(@parking)
  end

  def destroy
    @parking.destroy
    redirect_to parkings_path, status: :see_other
  end

  private

  def set_parking
    @parking = Parking.find(params[:id])
  end

  def parking_params
    params.require(:parking).permit(:address, :height, :width, :length, :description, :pass_code, :start_date, :end_date, :price, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ESO Parking</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render "shared/flashes" %>
    <%= yield %>
     <p class="notice"><%= notice %></p>
    <%= render 'shared/footer' %>
  </body>

</html>

app/views/pages/home.html.erb
<div class="banner">
    <div class = "title">
      <h1>ESO Parking</h1>
      <p><span data-controller="typed-js"></span>Solve your parking problems forever!</p>
    </div>
    <div class ="container_buttons">
      <%=  link_to parkings_path, class: "link-to-show" do%>
        <p class="button">Browse Parkings in your area</p>
      <% end %>
      <% if user_signed_in? %>
        <%=  link_to destroy_user_session_path, data: { turbo_method: :delete}, class: "link-to-login" do%>
          <p class="button">Log-off</p>
        <% end %>
      <% else %>
        <%=  link_to new_user_session_path, class: "link-to-login" do%>
          <p class="button">Log-in</p>
        <% end %>
      <% end %>
  </div>
</div>

<div class = "how-it-works">
    <h2 class = "text-center">How it works</h2>
    <div class = "container-cards">
      <div class = "card">

        <% if user_signed_in? %>
          <%=  link_to profile_path(), class: "link-to-login" do%>
          <%= cl_image_tag current_user.photo.key, class: "avatar-square", alt: "avatar-square" %>
          <h3>Profile</h3>
          <p>See my parkings and my bookings</p>
          <%end%>
        <%else%>
          <%=  link_to new_user_registration_path, class: "link-to-login" do%>
          <%= image_tag "profile.png"%>
          <h3>Sign-up</h3>
          <p>Create your account</p>
          <%end%>
        <%end%>
      </div>

      <div class = "card">
        <%= link_to new_parking_path, class: "link-to-show" do  %>
        <%= image_tag "land.png"%>
        <h3>Add a Parking space</h3>
        <p>You can show to other users your parking space available to land</p>
        <% end %>
      </div>
      <div class = "card">
        <%=  link_to parkings_path, class: "link-to-show" do%>
        <%= image_tag "browse.png" %>
        <h3>Browse parking space</h3>
        <p> search for parking spaces available in your area </p>
        <% end %>
      </div>
    </div>
  </div>

app/views/pages/profile.html.erb
<div id="profile"><h1 style="font-family:roboto"><strong>Profile</strong></h1></div>


<div class ="dashcontainer">



  <div class ="bookings", style="font-family:roboto; background-color: whitesmoke;">
      <h2 style="font-family:roboto"><strong>My bookings</strong></h2>
      <% if @bookings %>
        <% @bookings.each do |booking| %>
           <ul>
              <li><strong>Address:</strong> <%= booking.parking.address%> </li>
              <li><strong>Arrival:</strong> <%= booking.booking_start%></li>
              <li><strong>Depart:</strong>  <%= booking.booking_end%></li>
            </ul>
            <%if booking.confirmation == false%>
              <p class="grey">(Awaiting owner validation)</p>
            <%end%>
            <p><small><%= link_to "delete", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this booking?"}, class: 'text-danger' %></small></p>
          <% end %>
      <% else %>
      <p>you do not have any bookings completed yet</p>
      <% end %>
  </div>

  <div class ="parkings" style="font-family:roboto; background-color: white;">
    <h2 style="font-family:roboto">My Parkings</h2>
    <div class = "parking-info">
      <% if @parkings %>
        <% @parkings.each do |parking| %>
          <div class = "parking-info">
            <%=  link_to parking_path(parking), class: "link-to-show" do%>
              <div class="card-profile" style="background-color:lightbrown">
                <%= cl_image_tag parking.photos.first.key, width:200 %>
                <div class="card-profile-infos">
                  <h2 style="font-family:roboto"><%= parking.address %></h2>
                  <p> <%= parking.description.capitalize %> (<%= parking.width %>cm wide, <%= parking.height %>cm tall, and <%= parking.length %>cm long.)</p>
                  <div id = "bottom">
                    <p>Availability: <%= parking.start_date %></p>
                    <p><small><%= link_to "delete", parking_path(parking), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this parking?"}, class: 'text-danger' %></small></p>
                    <p id ="edit-button"> <%= link_to edit_parking_path(parking), class: "link-to-show" do %> edit </p><%end %>
                  </div>
                </div>
              </div>
            <%end%>
          </div>
          <div class="booking-confirm d-flex" style="font-family:roboto;">
            <%parking.bookings.each do |booking_by_parking|%>
              <div class="booking-parking" style="background-color: white; margin-bottom:4px">
                <p style="font-family:roboto"> Booking by </p>
                <h2 style="font-family:roboto"><%=booking_by_parking.user.first_name%> <%=booking_by_parking.user.last_name%> </h2>
                <%= cl_image_tag booking_by_parking.user.photo.key, class:"mini-avatar"%>
                <ul>
                  <li>For the <%=booking_by_parking.booking_start%></li>
                  <li>Until <%=booking_by_parking.booking_end%> </li>

                <%if booking_by_parking.confirmation == false %>
                  <%=link_to validate_booking_path(booking_by_parking), data: {turbo_method: :patch}, class:" icon yes" do%>
                  <i class="fa-solid fa-circle-check"></i>
                  <%end%>
                <%end%>
                <%=link_to booking_path(booking_by_parking), data: {turbo_method: :delete}, class:"icon non" do%>
                  <i class="fa-solid fa-circle-minus"></i>
                <%end%>
                </ul>
              </div>
            <%end%>
          </div>
        <%end%>

      <% else %>
        <p>you do not have any parkings registered yet</p>
      <% end %>
    </div>
  </div>
</div>

app/views/parkings/_info_window.html.erb
<div class="popup" >
  <%=  link_to parking do%>
    <div>
      <h2><%=  parking.address%></h2>
      <%= cl_image_tag parking.photos.first.key %>
    </div>
  <% end  %>
</div>

app/views/parkings/edit.html.erb
<div style="margin:50px">
  <div class="container py-5">
    <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
        <div class="bg-white rounded p-3 shadow">
          <h3>Edit your parking</h3>
          <%= simple_form_for @parking do |f| %>
            <%= f.input :address, placeholder: 'Parking' %>
            <%= f.input :height, placeholder: 'Height' %>
            <%= f.input :width, placeholder: 'Width' %>
            <%= f.input :length, placeholder: 'Length' %>
            <%= f.input :description, placeholder: 'Description' %>
            <%= f.input :pass_code, placeholder: 'Passcode' %>
            <%= f.input :start_date, placeholder: 'Available Start Date' %>
            <%= f.input :end_date, placeholder: 'Available End Date' %>
            <%= f.input :price, placeholder: 'Price per hour' %>
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
            <%= f.submit class: 'btn btn-flat' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/parkings/index.html.erb
<div style="margin-top:90px; margin-left:40px; ">
<h1 style ="font-family: roboto;"><strong>Look for some parkings!</strong></h1>
</div>
<div class= "index-split" style="margin-top: 30px">
  <ul style ="font-family: roboto;" >
    <% @parkings.each do |parking| %>
      <%=  link_to parking_path(parking), class: "link-to-show" do%>
        <div class="card-product">
          <%= cl_image_tag parking.photos.first.key, width:200 %>
          <div class="card-product-infos">
            <h2 style ="font-family: roboto;"><%= parking.address %></h2>
            <p> <%= parking.description %> (<%= parking.width %>cm wide, <%= parking.height %>cm tall, and <%= parking.length %>cm long.)</p>
            <p> Available dates: <%= parking.start_date %> to <%= parking.end_date %></p>
          </div>
        </div>
      <% end  %>
    <% end %>
  </ul>

  <div class="map-search">
    <div class= "map"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <div class="search" style ="font-family: roboto;">
      <%= form_with url: parkings_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
       params[:query],
       class: "form-control",
       placeholder: "Find a parking"
      %>
      <%= submit_tag "Search", class: "btn btn-primary"%>
      <% end %>
    </div>

   </div>
</div>

app/views/parkings/new.html.erb
<div class="container py-5" style="margin-top: 40px">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a new parking</h3>

        <%= simple_form_for @parking  do |f| %>
          <%= f.input :address, placeholder: 'Parking' %>
          <%= f.input :height, placeholder: 'Height (in cm)' %>
          <%= f.input :width, placeholder: 'Width (in cm)' %>
          <%= f.input :length, placeholder: 'Length (in cm)' %>
          <%= f.input :description, placeholder: 'Description' %>
          <%= f.input :pass_code, placeholder: 'Password', label: "Password" %>
          <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :price, placeholder: 'Price per hour' %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/parkings/show.html.erb
<div style="margin-top:70px; margin-left:30px; margin-right:30px; font-family:roboto">
  <div class = "title">
    <h1 style="font-family:roboto"><strong> <%=@parking.address%></strong></h1>
  </div>

  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= cl_image_tag @parking.photos[0].key, class:"d-block w-50 container h-100"  %>
      </div>
        <% @parking.photos[1..].each do |photo| %>
      <div class="carousel-item">
        <%= cl_image_tag photo.key, class:"d-block w-50 container h-100"  %>
      </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <div class= "contenaire">
    <div class="informations">
      <div class="host-informations">
        <%= cl_image_tag @parking.user.photo.key, class: "avatar-square", alt: "avatar-square" %>
        <p id="host-name"><%= @parking.user.first_name.capitalize %> <%= @parking.user.last_name.capitalize %></p>
      </div>
      <div class="informations-logement">
        <ul>
          <li>Address:  <%=@parking.address  %></li>
          <li><%= @parking.description %></li>
          <li>Dimension:  <%=@parking.height%>cm, <%= @parking.width%>cm, <%=@parking.length%>cm.</li>
          <li>Availability:  <%=@parking.start_date%> to <%=@parking.end_date%> </li>
        </ul>
      </div>
    </div>
    <div id="booking" style="font-family:roboto">
      <h2 class="price" style="font-family:roboto">Price:  <%=@parking.price %>$ per hour</h2>
      <%= simple_form_for([@parking, @booking]) do |f| %>
        <%= f.input :booking_start, as: :string, required: false, input_html: {class: "datepicker"}, label:"Booking start date:" %>
        <%= f.input :booking_end, as: :string, required: false, input_html: {class: "datepicker"}, label:"Booking end date:" %>
        <%= f.submit "Reserve!", class: "btn btn-primary", style: "margin-right: 20px" %>
      <% end %>
    </div>
    <div id="map"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>



<%# <div class="payer">
<div class="disponibilité"></div>
<div class="facture"></div>
</div>
</div>
</div> %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <footer>
    <ul class = "list_inline">
      <li class="inline"><a class="social_icon" href="https://arthur-littm.github.io/startup-landing/#"target="_blank"><i class="fa-brands fa-square-github"></i></a></li>
      <li class="inline"><a class="social_icon" href="https://arthur-littm.github.io/startup-landing/#"target="_blank"><i class="fa-brands fa-facebook"></i></a></li>
      <li class="inline"><a class="social_icon" href="https://arthur-littm.github.io/startup-landing/#"target="_blank"><i class="fa-brands fa-twitter"></i></a></li>
      <li class="inline"><a class="social_icon" href="https://arthur-littm.github.io/startup-landing/#" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
    </ul>
    <h2>Feel free to contact us ❤️</h2>
  </footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <%= link_to root_path do %>
    <%= image_tag "eso-parking.png", alt: "alttext", class: "logo" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
            <%= link_to "Browse", parkings_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to profile_path, class: "nav-link", id:"name" do %>
            <p><%=current_user.first_name.capitalize%> <%=current_user.last_name.capitalize%></p>
            <%end%>
        </li>
         <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, width: 40, height: 40, crop: :fill, class: "avatar avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <p class ="dropdown-item"><%= link_to "Profile", profile_path, class: "nav-link"%></p>
              <p class ="dropdown-item"><%= link_to "New Parking", new_parking_path, class: "nav-link" %></p>
              <p class ="dropdown-item"><%= link_to "Log off", destroy_user_session_path, data: { turbo_method: :delete}, class: "link-to-login" %></p>
            </div>
          </li>
      <% else %>
        <li class="nav-item active">
            <%= link_to "Log-in", new_user_session_path, class: "nav-link" %>
        </li>
               <li class="nav-item active">
            <%= link_to "Browse", parkings_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>